{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app.fullname" . }}-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if eq .Values.sealedSecret.scope "namespace-wide" }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  {{- else if eq .Values.sealedSecret.scope "cluster-wide" }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  {{- end }}
spec:
  encryptedData:
    {{- range $k, $v := .Values.sealedSecret.encryptedData }}
    {{ $k }}: {{ $v }}
    {{- end }}
  template:
    metadata:
      name: {{ include "app.fullname" . }}-secret
    type: Opaque
{{- end }}
